# Site settings
title: Enjoying Sucking
header-img: img/home-bg.png
email: taylor@thewilliams.net
copyright_name: Taylor-Williams
description: > # this means to ignore newlines until "baseurl:"
  learning to enjoying sucking and using it to become skilled
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Taylor-Williams
learn_profile: Taylor-Williams
email_username: taylor@thewilliams.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
